In [2]:
import requests
from bs4 import BeautifulSoup

# Send a GET request to the webpage
url = 'https://www.espn.com/mens-college-basketball/stats/player'
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the webpage
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find the table containing player statistics
    table = soup.find('table', class_='Table Table--align-right Table--fixed Table--fixed-left')

    if table:
        # Extract data from the table
        headers = [header.text.strip() for header in table.find_all('th')]
        players_data = []
        for row in table.find_all('tr'):
            player_info = [data.text.strip() for data in row.find_all('td')]
            if player_info:  # Ensure it's not a header row
                players_data.append(player_info)

        # Print the headers and some player data for testing
        print(headers)
        print(players_data[:5])  # Print data for the first 5 players as an example
    else:
        print("Table not found on the webpage.")
else:
    print("Failed to retrieve the webpage.")

Failed to retrieve the webpage.

In [3]:
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import pandas as pd

# Initialize WebDriver
driver = webdriver.Chrome()  # Assuming you are using Chrome
base_url = 'https://www.espn.com/mens-college-basketball/stats/player'
url = base_url

# Assume driver is already initialized
driver.get(url)

# Define a function to click the "Show More" button using JavaScript
def click_show_more():
    js_script = "document.querySelector('.loadMore__link').click();"
    driver.execute_script(js_script)
    time.sleep(5)  # Wait for data to load

# Click the "Show More" button multiple times to load all data
num_clicks = 14  # Number of times to click "Show More"
for _ in range(num_clicks):
    click_show_more()

# Get the page source after loading all data
page_source = driver.page_source

# Close the Selenium WebDriver
driver.quit()

# Parse the page source with BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Find the table containing player stats
table = soup.find('table', class_='Table Table--align-right')

# Initialize lists to store data
rows_data = []

# Define the columns based on the header row
columns = [header.text for header in table.find_all('th', class_='Table__TH')]

# Find all rows in the table body
rows = table.find('tbody').find_all('tr', class_='Table__TR')

# Loop through each row and extract data
for row in rows:
    row_data = [cell.text.strip() for cell in row.find_all('td', class_='Table__TD')]
    rows_data.append(row_data)

# Create a DataFrame
df = pd.DataFrame(rows_data, columns=columns)

# Display the DataFrame
print(len(df))

df.head()

750

,POS,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,FT%,REB,AST,STL,BLK,TO
0,C,39,32.0,25.2,8.6,13.8,62.3,0.0,0.1,50.0,7.9,11.2,71.1,12.2,2.0,0.3,2.2,2.3
1,G,34,33.8,24.0,7.7,17.7,43.5,2.4,6.8,35.3,6.2,7.6,80.8,2.8,4.2,1.3,0.1,3.6
2,G,32,34.0,23.0,6.8,14.4,47.5,2.4,6.7,36.2,6.9,8.6,80.1,4.0,2.3,1.0,0.9,2.0
3,G,33,37.9,22.5,8.0,19.4,41.4,3.8,10.2,37.1,2.6,3.1,86.1,5.2,3.3,1.3,0.5,2.1
4,G,32,36.7,22.2,6.6,15.6,42.2,2.1,5.8,36.8,6.8,7.7,89.0,4.1,6.1,1.5,0.3,3.3

In [4]:
# Initialize WebDriver
driver = webdriver.Chrome()  # Assuming you are using Chrome
base_url = 'https://www.espn.com/mens-college-basketball/stats/player'
url = base_url

# Assume driver is already initialized
driver.get(url)

# Define a function to click the "Show More" button using JavaScript
def click_show_more():
    js_script = "document.querySelector('.loadMore__link').click();"
    driver.execute_script(js_script)
    time.sleep(5)  # Wait for data to load

# Click the "Show More" button multiple times to load all data
num_clicks = 14  # Number of times to click "Show More"
for _ in range(num_clicks):
    click_show_more()

# Get the page source after loading all data
page_source = driver.page_source

# Close the Selenium WebDriver
driver.quit()

# Parse the page source with BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Find the table containing player stats
table2 = soup.find('table', class_="Table Table--align-right Table--fixed Table--fixed-left")

# Initialize lists to store data
rows_data2 = []

# Find all rows in the table body
rows2 = soup.find_all('tr', class_='Table__TR')


# Loop through each row and extract data
for row in rows2:
    anchor_tag = row.find('a', class_='AnchorLink')
    if anchor_tag is not None:
        row_data2 = anchor_tag.text.strip()
        rows_data2.append(row_data2)


# Create a DataFrame
df2 = pd.DataFrame(rows_data2)

#Display the DataFrame
print(len(df2))

df2.head()

751

                      0
0             Zach Edey
1          Tommy Bruner
2  Terrence Shannon Jr.
3          Tyler Thomas
4        Xavier Johnson

In [5]:
df.head()

,POS,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,FT%,REB,AST,STL,BLK,TO
0,C,39,32.0,25.2,8.6,13.8,62.3,0.0,0.1,50.0,7.9,11.2,71.1,12.2,2.0,0.3,2.2,2.3
1,G,34,33.8,24.0,7.7,17.7,43.5,2.4,6.8,35.3,6.2,7.6,80.8,2.8,4.2,1.3,0.1,3.6
2,G,32,34.0,23.0,6.8,14.4,47.5,2.4,6.7,36.2,6.9,8.6,80.1,4.0,2.3,1.0,0.9,2.0
3,G,33,37.9,22.5,8.0,19.4,41.4,3.8,10.2,37.1,2.6,3.1,86.1,5.2,3.3,1.3,0.5,2.1
4,G,32,36.7,22.2,6.6,15.6,42.2,2.1,5.8,36.8,6.8,7.7,89.0,4.1,6.1,1.5,0.3,3.3

In [7]:
df2.rename(columns={0: 'Name'}, inplace=True)

In [8]:
# Convert to Float
df['GP'] = df['GP'].astype(float)
df['MIN'] = df['MIN'].astype(float)
df['PTS'] = df['PTS'].astype(float)
df['FGM'] = df['FGM'].astype(float)
df['FGA'] = df['FGA'].astype(float)
df['3PM'] = df['3PM'].astype(float)
df['3PA'] = df['3PA'].astype(float)
df['FTM'] = df['FTM'].astype(float)
df['FTA'] = df['FTA'].astype(float)
df['REB'] = df['REB'].astype(float)
df['AST'] = df['AST'].astype(float)
df['STL'] = df['STL'].astype(float)
df['BLK'] = df['BLK'].astype(float)
df['TO'] = df['TO'].astype(float)

# Calculate ast_tov_ratio
df['ast_tov'] = df['AST'] / df['TO']

# Calculate eFG
df['eFG'] = (df['FGM'] + 0.5 * df['3PM']) / df['FGA']

In [9]:
# Combine
df["Name"] = df2["Name"]

In [10]:
# Remove Columns No Longer Needed
df.drop(columns=['TO', 'POS'], inplace=True)

# Re order Columns
df = df[['Name', 'GP', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%', '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'eFG', 'REB', 'AST', 'STL', 'BLK', 'ast_tov']]
df.head()

,Name,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,FT%,eFG,REB,AST,STL,BLK,ast_tov
0,Zach Edey,39.0,32.0,25.2,8.6,13.8,62.3,0.0,0.1,50.0,7.9,11.2,71.1,0.623188,12.2,2.0,0.3,2.2,0.869565
1,Tommy Bruner,34.0,33.8,24.0,7.7,17.7,43.5,2.4,6.8,35.3,6.2,7.6,80.8,0.502825,2.8,4.2,1.3,0.1,1.166667
2,Terrence Shannon Jr.,32.0,34.0,23.0,6.8,14.4,47.5,2.4,6.7,36.2,6.9,8.6,80.1,0.555556,4.0,2.3,1.0,0.9,1.150000
3,Tyler Thomas,33.0,37.9,22.5,8.0,19.4,41.4,3.8,10.2,37.1,2.6,3.1,86.1,0.510309,5.2,3.3,1.3,0.5,1.571429
4,Xavier Johnson,32.0,36.7,22.2,6.6,15.6,42.2,2.1,5.8,36.8,6.8,7.7,89.0,0.490385,4.1,6.1,1.5,0.3,1.848485

In [11]:
df.to_csv('top750.csv', index=False)